
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    command: npm run start:dev

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai:/app
