services:
  postgres:
    image: postgres:15
    expose:
      - "5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    image: dudwns0921/guru:frontend-latest
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: always  

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.prod
    image: dudwns0921/guru:backend-latest
    ports:
      - "8082:3000"
    networks:
      - app-network
    restart: always
    env_file:
      - ./.env
    depends_on:
      - postgres

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile.prod
    image: dudwns0921/guru:ai-latest
    expose:
      - "8000"
    networks:
      - app-network
    restart: always

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge