export const seedUsers = [
  {
    id: 1,
    email: 'user1@example.com',
    name: '김유저',
    password: 'hashed_password_1', // 실제로는 해시된 비밀번호
    isActive: true,
    createdAt: new Date('2025-07-01T10:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 2,
    email: 'instructor1@example.com',
    name: '박강사',
    password: 'hashed_password_2',
    isActive: true,
    createdAt: new Date('2025-07-02T12:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 3,
    email: 'admin@example.com',
    name: '이관리자',
    password: 'hashed_password_3',
    isActive: true,
    createdAt: new Date('2025-07-03T14:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 4,
    email: 'user2@example.com',
    name: '최수강생',
    password: 'hashed_password_4',
    isActive: false, // 비활성화된 유저 예시
    createdAt: new Date('2025-07-04T16:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 5,
    email: 'instructor2@example.com',
    name: '정강사',
    password: 'hashed_password_5',
    isActive: true,
    createdAt: new Date('2025-07-05T18:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 6,
    email: 'user3@example.com',
    name: '윤수강생',
    password: 'hashed_password_6',
    isActive: true,
    createdAt: new Date('2025-07-06T08:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 7,
    email: 'instructor3@example.com',
    name: '한강사',
    password: 'hashed_password_7',
    isActive: true,
    createdAt: new Date('2025-07-07T09:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 8,
    email: 'user4@example.com',
    name: '장수강생',
    password: 'hashed_password_8',
    isActive: false,
    createdAt: new Date('2025-07-08T11:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 9,
    email: 'user5@example.com',
    name: '홍유저',
    password: 'hashed_password_9',
    isActive: true,
    createdAt: new Date('2025-07-09T13:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
  {
    id: 10,
    email: 'instructor4@example.com',
    name: '최강사',
    password: 'hashed_password_10',
    isActive: true,
    createdAt: new Date('2025-07-10T15:00:00Z'),
    enrollments: [],
    reviews: [],
    searchHistory: [],
  },
]
