export const seedCourses = [
  {
    title: 'React 완전 정복',
    description: 'React의 기초부터 고급 패턴까지 완전히 마스터하는 실무 중심 강의입니다.',
    instructor: '김리액트',
    price: 99000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=1',
    tags: ['React', 'JavaScript', 'Frontend', 'SPA', 'Hooks'],
  },
  {
    title: 'Node.js 백엔드 개발',
    description: 'Node.js, Express, MongoDB를 활용한 RESTful API 개발 완전 가이드',
    instructor: '이노드',
    price: 120000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=2',
    tags: ['Node.js', 'Express', 'Backend', 'API', 'JavaScript'],
  },
  {
    title: 'TypeScript 마스터클래스',
    description: 'JavaScript 개발자를 위한 TypeScript 완전 정복 과정',
    instructor: '박타입',
    price: 89000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=3',
    tags: ['TypeScript', 'JavaScript', 'Type Safety', 'ES6+', 'Development'],
  },
  {
    title: 'Python 데이터 분석',
    description: 'Pandas, NumPy, Matplotlib을 활용한 실무 데이터 분석',
    instructor: '최파이썬',
    price: 150000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=4',
    tags: ['Python', 'Data Analysis', 'Pandas', 'NumPy', 'Visualization'],
  },
  {
    title: 'Vue.js 3 완벽 가이드',
    description: 'Vue.js 3의 Composition API부터 실무 프로젝트까지',
    instructor: '정뷰',
    price: 110000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=5',
    tags: ['Vue.js', 'Frontend', 'Composition API', 'SPA', 'JavaScript'],
  },
  {
    title: 'AWS 클라우드 아키텍처',
    description: 'AWS 서비스를 활용한 확장 가능한 클라우드 시스템 설계',
    instructor: '이클라우드',
    price: 200000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=6',
    tags: ['AWS', 'Cloud', 'DevOps', 'Infrastructure', 'Serverless'],
  },
  {
    title: 'Docker & Kubernetes',
    description: '컨테이너 기반 개발부터 쿠버네티스 운영까지',
    instructor: '장도커',
    price: 180000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=7',
    tags: ['Docker', 'Kubernetes', 'DevOps', 'Container', 'Orchestration'],
  },
  {
    title: 'Next.js 풀스택 개발',
    description: 'Next.js로 만드는 현대적인 풀스택 웹 애플리케이션',
    instructor: '김넥스트',
    price: 140000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=8',
    tags: ['Next.js', 'React', 'Fullstack', 'SSR', 'Vercel'],
  },
  {
    title: 'MongoDB 데이터베이스',
    description: 'NoSQL 데이터베이스 MongoDB 실무 활용법',
    instructor: '이몽고',
    price: 95000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=9',
    tags: ['MongoDB', 'NoSQL', 'Database', 'Backend', 'Aggregation'],
  },
  {
    title: 'GraphQL API 개발',
    description: 'GraphQL을 활용한 효율적인 API 설계와 구현',
    instructor: '박그래프',
    price: 125000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=10',
    tags: ['GraphQL', 'API', 'Backend', 'Apollo', 'Query Language'],
  },
  {
    title: 'React Native 모바일 앱',
    description: 'React Native로 iOS/Android 앱 동시 개발하기',
    instructor: '최모바일',
    price: 160000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=11',
    tags: ['React Native', 'Mobile', 'iOS', 'Android', 'Cross Platform'],
  },
  {
    title: 'Spring Boot 마스터',
    description: 'Java Spring Boot를 활용한 엔터프라이즈 애플리케이션 개발',
    instructor: '정스프링',
    price: 175000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=12',
    tags: ['Spring Boot', 'Java', 'Backend', 'Enterprise', 'JPA'],
  },
  {
    title: 'Flutter 앱 개발',
    description: 'Dart와 Flutter로 크로스플랫폼 모바일 앱 만들기',
    instructor: '김플러터',
    price: 145000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=13',
    tags: ['Flutter', 'Dart', 'Mobile', 'Cross Platform', 'Google'],
  },
  {
    title: 'Redis 캐싱 전략',
    description: '고성능 웹 애플리케이션을 위한 Redis 활용법',
    instructor: '이레디스',
    price: 85000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=14',
    tags: ['Redis', 'Caching', 'Performance', 'Database', 'Memory'],
  },
  {
    title: 'Elasticsearch 검색엔진',
    description: '대용량 데이터 검색과 분석을 위한 Elasticsearch 마스터',
    instructor: '박검색',
    price: 190000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=15',
    tags: ['Elasticsearch', 'Search', 'Analytics', 'Big Data', 'Kibana'],
  },
  {
    title: 'Svelte 프론트엔드',
    description: '가장 빠른 프론트엔드 프레임워크 Svelte 완전 정복',
    instructor: '최스벨트',
    price: 105000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=16',
    tags: ['Svelte', 'Frontend', 'Performance', 'Compiler', 'JavaScript'],
  },
  {
    title: 'PostgreSQL 데이터베이스',
    description: '관계형 데이터베이스 PostgreSQL의 고급 기능 활용',
    instructor: '장포스트',
    price: 115000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=17',
    tags: ['PostgreSQL', 'SQL', 'Database', 'Relational', 'ACID'],
  },
  {
    title: 'Nginx 웹서버',
    description: '고성능 웹서버 Nginx 설정과 최적화 가이드',
    instructor: '김엔진엑스',
    price: 75000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=18',
    tags: ['Nginx', 'Web Server', 'Load Balancer', 'Reverse Proxy', 'Performance'],
  },
  {
    title: 'Jenkins CI/CD',
    description: '자동화된 배포 파이프라인 구축과 DevOps 실무',
    instructor: '이젠킨스',
    price: 135000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=19',
    tags: ['Jenkins', 'CI/CD', 'DevOps', 'Automation', 'Pipeline'],
  },
  {
    title: 'Golang 백엔드 개발',
    description: 'Go 언어로 만드는 고성능 마이크로서비스',
    instructor: '박고랭',
    price: 155000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=20',
    tags: ['Go', 'Golang', 'Backend', 'Microservices', 'Concurrency'],
  },
  {
    title: 'Rust 시스템 프로그래밍',
    description: '메모리 안전성과 성능을 보장하는 Rust 언어 마스터',
    instructor: '최러스트',
    price: 170000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=21',
    tags: ['Rust', 'System Programming', 'Memory Safety', 'Performance', 'Concurrency'],
  },
  {
    title: 'Tailwind CSS 디자인',
    description: '유틸리티 퍼스트 CSS 프레임워크로 빠른 UI 개발',
    instructor: '정테일윈드',
    price: 80000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=22',
    tags: ['Tailwind CSS', 'CSS', 'Frontend', 'UI', 'Utility First'],
  },
  {
    title: 'WebAssembly 고성능 웹',
    description: '네이티브 성능의 웹 애플리케이션 개발하기',
    instructor: '김웹어셈',
    price: 195000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=23',
    tags: ['WebAssembly', 'WASM', 'Performance', 'C++', 'Rust'],
  },
  {
    title: 'Three.js 3D 웹',
    description: '웹에서 구현하는 인터랙티브 3D 그래픽스',
    instructor: '이쓰리',
    price: 165000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=24',
    tags: ['Three.js', '3D', 'WebGL', 'Graphics', 'Animation'],
  },
  {
    title: 'D3.js 데이터 시각화',
    description: '데이터를 아름다운 인터랙티브 차트로 변환하기',
    instructor: '박데이터',
    price: 130000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=25',
    tags: ['D3.js', 'Data Visualization', 'SVG', 'Charts', 'Interactive'],
  },
  {
    title: 'Socket.io 실시간 통신',
    description: '실시간 채팅과 알림 시스템 구축하기',
    instructor: '최소켓',
    price: 100000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=26',
    tags: ['Socket.io', 'Real-time', 'WebSocket', 'Chat', 'Node.js'],
  },
  {
    title: 'Prisma ORM',
    description: '타입 안전한 데이터베이스 액세스를 위한 Prisma 활용법',
    instructor: '장프리즈마',
    price: 110000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=27',
    tags: ['Prisma', 'ORM', 'Database', 'TypeScript', 'Type Safety'],
  },
  {
    title: 'Stripe 결제 시스템',
    description: '안전하고 신뢰할 수 있는 온라인 결제 시스템 구축',
    instructor: '김결제',
    price: 140000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=28',
    tags: ['Stripe', 'Payment', 'E-commerce', 'API', 'Security'],
  },
  {
    title: 'Firebase 백엔드',
    description: 'Google Firebase로 서버리스 백엔드 구축하기',
    instructor: '이파이어베이스',
    price: 125000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=29',
    tags: ['Firebase', 'Serverless', 'Backend', 'Google', 'NoSQL'],
  },
  {
    title: 'Supabase 개발',
    description: '오픈소스 Firebase 대안 Supabase 완전 활용',
    instructor: '박수파베이스',
    price: 115000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=30',
    tags: ['Supabase', 'Backend', 'PostgreSQL', 'Real-time', 'Open Source'],
  },
  {
    title: 'TensorFlow.js 머신러닝',
    description: '웹에서 구현하는 머신러닝과 AI 모델',
    instructor: '최텐서플로우',
    price: 220000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=31',
    tags: ['TensorFlow.js', 'Machine Learning', 'AI', 'Neural Networks', 'JavaScript'],
  },
  {
    title: 'Electron 데스크톱 앱',
    description: '웹 기술로 만드는 크로스플랫폼 데스크톱 애플리케이션',
    instructor: '정일렉트론',
    price: 150000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=32',
    tags: ['Electron', 'Desktop', 'Cross Platform', 'Node.js', 'Chromium'],
  },
  {
    title: 'Deno 런타임',
    description: '차세대 JavaScript/TypeScript 런타임 Deno 마스터',
    instructor: '김데노',
    price: 135000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=33',
    tags: ['Deno', 'JavaScript', 'TypeScript', 'Runtime', 'Security'],
  },
  {
    title: 'Bun 자바스크립트 런타임',
    description: '초고속 JavaScript 런타임 Bun 완전 활용법',
    instructor: '이번',
    price: 120000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=34',
    tags: ['Bun', 'JavaScript', 'Runtime', 'Performance', 'Bundler'],
  },
  {
    title: 'Vite 빌드 도구',
    description: '빠른 개발과 빌드를 위한 차세대 프론트엔드 도구',
    instructor: '박비트',
    price: 85000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=35',
    tags: ['Vite', 'Build Tool', 'Frontend', 'ES Modules', 'HMR'],
  },
  {
    title: 'Remix 풀스택 프레임워크',
    description: '웹 표준 기반의 현대적인 풀스택 React 프레임워크',
    instructor: '최리믹스',
    price: 155000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=36',
    tags: ['Remix', 'React', 'Fullstack', 'Web Standards', 'SSR'],
  },
  {
    title: 'SolidJS 반응형 UI',
    description: '진정한 반응형을 구현하는 고성능 UI 라이브러리',
    instructor: '장솔리드',
    price: 125000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=37',
    tags: ['SolidJS', 'Reactive', 'Frontend', 'Performance', 'Fine-grained'],
  },
  {
    title: 'Qwik 즉시 로딩',
    description: '즉시 로딩되는 웹 애플리케이션을 위한 Qwik 프레임워크',
    instructor: '김퀵',
    price: 140000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=38',
    tags: ['Qwik', 'Resumability', 'Performance', 'SSR', 'Lazy Loading'],
  },
  {
    title: 'Astro 정적 사이트',
    description: '콘텐츠 중심의 초고속 정적 사이트 생성기',
    instructor: '이아스트로',
    price: 110000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=39',
    tags: ['Astro', 'Static Site', 'Performance', 'Content', 'Islands'],
  },
  {
    title: 'Nuxt.js Vue 프레임워크',
    description: 'Vue.js 기반의 프로덕션 레디 웹 프레임워크',
    instructor: '박넉스트',
    price: 145000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=40',
    tags: ['Nuxt.js', 'Vue.js', 'SSR', 'Static Site', 'Universal'],
  },
  {
    title: 'SvelteKit 풀스택',
    description: 'Svelte 기반의 풀스택 웹 애플리케이션 프레임워크',
    instructor: '최스벨트킷',
    price: 130000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=41',
    tags: ['SvelteKit', 'Svelte', 'Fullstack', 'SSR', 'Performance'],
  },
  {
    title: 'Turbo 모노리포',
    description: '고성능 JavaScript/TypeScript 모노리포 도구',
    instructor: '정터보',
    price: 115000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=42',
    tags: ['Turbo', 'Monorepo', 'Build System', 'Caching', 'Performance'],
  },
  {
    title: 'pnpm 패키지 매니저',
    description: '빠르고 효율적인 JavaScript 패키지 매니저',
    instructor: '김패키지',
    price: 70000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=43',
    tags: ['pnpm', 'Package Manager', 'Node.js', 'Performance', 'Disk Space'],
  },
  {
    title: 'esbuild 초고속 빌드',
    description: 'Go로 작성된 초고속 JavaScript 번들러',
    instructor: '이빌드',
    price: 90000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=44',
    tags: ['esbuild', 'Bundler', 'Go', 'Performance', 'JavaScript'],
  },
  {
    title: 'SWC 컴파일러',
    description: 'Rust 기반의 초고속 JavaScript/TypeScript 컴파일러',
    instructor: '박컴파일',
    price: 95000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=45',
    tags: ['SWC', 'Compiler', 'Rust', 'JavaScript', 'TypeScript'],
  },
  {
    title: 'Playwright 테스팅',
    description: '현대적인 웹 애플리케이션을 위한 end-to-end 테스팅',
    instructor: '최테스트',
    price: 120000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=46',
    tags: ['Playwright', 'E2E Testing', 'Automation', 'Cross Browser', 'Microsoft'],
  },
  {
    title: 'Cypress E2E 테스트',
    description: '개발자 친화적인 end-to-end 테스팅 프레임워크',
    instructor: '장사이프레스',
    price: 105000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=47',
    tags: ['Cypress', 'E2E Testing', 'JavaScript', 'Automation', 'Developer Tools'],
  },
  {
    title: 'Jest 단위 테스트',
    description: 'JavaScript 애플리케이션을 위한 포괄적인 테스팅 프레임워크',
    instructor: '김제스트',
    price: 85000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=48',
    tags: ['Jest', 'Unit Testing', 'JavaScript', 'Mocking', 'Snapshot'],
  },
  {
    title: 'MSW Mock Service',
    description: 'Service Worker를 활용한 API 모킹 라이브러리',
    instructor: '이목킹',
    price: 95000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=49',
    tags: ['MSW', 'API Mocking', 'Service Worker', 'Testing', 'REST'],
  },
  {
    title: 'Storybook 컴포넌트',
    description: 'UI 컴포넌트 개발과 테스팅을 위한 도구',
    instructor: '박스토리북',
    price: 110000,
    thumbnailUrl: 'https://picsum.photos/400/200?random=50',
    tags: ['Storybook', 'UI Components', 'Design System', 'Testing', 'Documentation'],
  },
]
